2020-03-17 14:37:56,853 ERROR: Exception on / [GET] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 20, in index
    return render_template("workersInShop")
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: workersInShop
2020-03-17 14:39:31,926 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 14:41:48,902 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 14:42:41,069 ERROR: Exception on /setcookie [POST] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 39, in setcookie
    return redirect (url_for('workersInShop',shop=shop))
NameError: name 'shop' is not defined
2020-03-17 14:45:30,021 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 14:52:42,308 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 15:00:43,672 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 15:01:29,523 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 15:22:28,069 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 15:24:20,682 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 15:24:39,078 ERROR: Exception on /setcookie [POST] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 31, in setcookie
    return redirect (url_for('workersInShop',shopID=shopID))
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'workersInShop' with values ['shopID']. Did you forget to specify values ['shop']?
2020-03-17 15:28:12,872 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
2020-03-17 15:29:11,667 ERROR: Exception on /setcookie [POST] [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\routes.py", line 31, in setcookie
    return redirect (url_for('workersInShop',shopID=shopID))
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'workersInShop' with values ['shopID']. Did you forget to specify values ['shop']?
2020-03-17 15:34:04,518 INFO: Check In startup [in c:\Users\richa\OneDrive\Projects\AzureWorkersInShop\app\__init__.py:29]
